#pragma config(Motor,  port2,           wheel,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           third,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		motor[wheel] = vexRT[Ch1];
		motor[arm] = vexRT[Ch3];

		if (vexRT[Btn5U] == 1)
			{
			motor[third] = -127;
			}
		if (vexRT[Btn6U] == 1)
			{
			motor[third] = 127;
			}
		else
			{
				motor[third] = 0;
			}
	}
}
