#pragma config(Motor,  port2,           svo1,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int Svo1pos;
	Svo1pos= -127;
	motor[svo1]=Svo1pos;

while(1==1)
	{
		if(vexRT[Btn8R]==1)
			{
				Svo1pos += 40;
				motor[svo1]=Svo1pos;
				wait1Msec(200);
			}
			else{
				if(vexRT[Btn8L]==1)
					{
						Svo1pos = Svo1pos-40;
						motor[svo1]=Svo1pos;
						wait1Msec(200);
					}
			}

			}
	}
